version: "3.8"
   
services:

    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_USER=user_db
            - POSTGRES_PASSWORD=testing321
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        ports:
          - 6379:6379
        volumes:
          - ./redisdb:/var/lib/redis
    
    celery:
        build: .
        command: celery -A todo worker -l INFO
        volumes:
            - ./:/usr/src/todoapp
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
volumes:
    pgdata:
    redisdb: